### PR TITLE
Fix updating checkbox state and avoid issues due to duplicate sidebar element

### LINKED ISSUE #2580: Usage of tasklist in description deletes entire description
**Describe the bug**
When check off tasks of a markdown task list, the entire description will be deleted.

**To Reproduce**
1. create a task list

```
- [ ] a
- [ ] b
- [ ] c
```

2. check off one task after each other. 
3. you won't reach task "c", because after check off "b", everything is deleted.

It's also deleted in the database.

**Expected behavior**

description won't be deleted and the tasks list is just checked off.

**Screenshots**

deckbug2

**Client details:**
 - OS: linux
 - Browser firefox
 - Version 82.0.2
 - Device: desktop
 - Deck 1.2.1
 - Nextcloud 20.0.1.1
 - PHP 7.4.11

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #2580 

Besides the fix for replacing the proper description this also required some adjustment to make sure that the actual card sidebar was not hidden in the DOM during editing in the modal.

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -37,7 +37,7 @@
 			</div>
 		</Modal>
 
-		<router-view v-show="!cardDetailsInModal || !$route.params.cardId" name="sidebar" />
+		<router-view name="sidebar" :visible="!cardDetailsInModal || !$route.params.cardId" />
```
Comment (skjnldsv) [inline src/App.vue:40]: Can't use v-if directly on the router-view?

Comment (juliushaertl) [reply src/App.vue:40]: There seems to be some issue with the nested router views that are used for sub-routes, where the router tried to render the component to a non-existing router-view element then. That is why I went that way for now. But I have that on my list to investigate further, so this is more a temporary workaround.

**Review by skjnldsv — APPROVED** [review]

**Comment by der-flo** [comment]
A timely release would be awesome because of the accidental data loss happening with a wrong mouse click.
