### PR TITLE
Avoid reusing the existing route object to make navigation work properly

### LINKED ISSUE #2911: Original board not accessible after cloning a board (unless refreshing page)
**Describe the bug**
After cloning a board, the original board cannot be accessed until I refresh the site.

**To Reproduce**
1. Create a board "my project" in Deck
3. Click on "Clone board"
4. See a new board "my project (copy)" in the list and be already in it in the main window
5. Click on "my project" in the list to switch back to the original board

**Expected behavior**
View remains on the copied board.
It doesn't matter how many boards I have in the list or how many boards I clone. After cloning a board, I can always only access the respective clone.
After refreshing the page however, everything works fine again.

**Screenshots**
Peek 2021-03-24 14-08

**Client details:**
 - Browser: Chrome + Firefox
 - Version NC 21.0.0, Deck 1.3.1

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #2911

### CODE REVIEW

File: src/components/navigation/AppNavigationBoard.vue [hunk 1]
```diff
@@ -298,11 +294,6 @@ export default {
 		cancelEdit(e) {
 			this.editing = false
 		},
-		showSidebar() {
```
Comment (juliushaertl) [inline src/components/navigation/AppNavigationBoard.vue:301]: Not used anywhere and was duplicate with the actionDetails method

**Review by ChristophWurst — APPROVED** [review]
