### PR TITLE
Only try to extract first part of the explode result

### LINKED ISSUE #2522: Error: Undefined offset: 1 at /var/www/html/custom_apps/deck/lib/Service/ConfigService.php#68 in 1.2.0 beta1
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Error message in the Nextcloud logs after installing 1.2.0 beta1:

Error: Undefined offset: 1 at /var/www/html/custom_apps/deck/lib/Service/ConfigService.php#68

**To Reproduce**
1. Go to Logs and see error messages

**Expected behavior**
No errors

<details>
<summary>Server details</summary>

**Operating system**: 

**Web server:** Official docker

**Database:** Postgres 13

**Nextcloud version:** 20.0.1

**Where did you install Nextcloud from:** officical Docker

**List of activated apps:**

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - announcementcenter: 4.0.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - deck: 1.2.0-beta1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_automatedtagging: 1.10.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.0.4
  - groupfolders: 8.1.1
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.7.0
  - metadata: 0.12.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - occweb: 0.0.7
  - onlyoffice: 6.1.0
  - password_policy: 1.10.1
  - polls: 1.6.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.1
  - survey_client: 1.8.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.0.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_pdf_converter: 1.5.0
  - workflow_script: 1.5.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - photos
  - support
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tsmd.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.tsmd.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "occweb",
            "polls"
        ],
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": {
            "1": "HTTP_X_FORWARDED",
            "2": "HTTP_FORWARDED_FOR",
            "3": "HTTP_FORWARDED",
            "0": "HTTP_X_FORWARDED_FOR"
        },
        "overwritehost": "cloud.tsmd.de",
        "overwriteprotocol": "https",
        "default_language": "de",
        "default_locale": "de_DE",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/var\/www\/html\/data\/skeleton",
        "updater.release.channel": "stable",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,30"
    }
}
```

**Are you using an external user-backend, if yes which one:** No

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"T9HQqeMirWqp1iNB9m68","level":3,"time":"2020-11-11T16:36:06+00:00","remoteAddr":"31.19.137.59","user":"christian.hartmann","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/christian.hartmann/","message":{"Exception":"Error","Message":"Undefined offset: 1 at /var/www/html/custom_apps/deck/lib/Service/ConfigService.php#68","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/deck/lib/Service/ConfigService.php","line":68,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined offset: 1","/var/www/html/custom_apps/deck/lib/Service/ConfigService.php",68,{"key":"calendar","result":null,"scope":"calendar"}]},{"file":"/var/www/html/custom_apps/deck/lib/DAV/CalendarPlugin.php","line":44,"function":"get","class":"OCA\\Deck\\Service\\ConfigService","type":"->","args":["calendar"]},{"function":"__construct","class":"OCA\\Deck\\DAV\\CalendarPlugin","type":"->","args":[{"__class__":"OCA\\Deck\\DAV\\DeckCalendarBackend"},{"__class__":"OCA\\Deck\\Service\\ConfigService"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OCA\\Deck\\DAV\\DeckCalendarBackend"},{"__class__":"OCA\\Deck\\Service\\ConfigService"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Deck\\DAV\\CalendarPlugin","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Deck\\DAV\\CalendarPlugin"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":455,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Deck\\DAV\\CalendarPlugin"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":140,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Deck\\DAV\\CalendarPlugin"]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":290,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Deck\\DAV\\CalendarPlugin"]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":159,"function":"loadSabreCalendarPluginsFromInfoXml","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[["OCA\\Deck\\DAV\\CalendarPlugin"]]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":103,"function":"populate","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":311,"function":"getAppPlugins","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"OCA\\DAV\\{closure}","class":"OCA\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PROPFIND",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":325,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":167,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Linux) mirall/3.0.3git (Nextcloud)","version":"20.0.1.1","id":"5fac12f73351d"}
```

#### Browser log
```
No entries regarding this error
```

</details>

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #2522 

As we only use the first result anyways we can safely ignore the second part if one exists.

cc @Chartman123

### CODE REVIEW

File: lib/Service/ConfigService.php [hunk 1]
```diff
@@ -65,7 +65,7 @@ public function getAll(): array {
 
 	public function get($key) {
 		$result = null;
-		[$scope, $id] = explode(':', $key, 2);
+		[$scope] = explode(':', $key, 2);
```
Comment (ChristophWurst) [inline lib/Service/ConfigService.php:68]:
```suggestion
		[$scope] = explode(':', $key, 1);
```

if you don't care about the rest :)

**Review by ChristophWurst — APPROVED** [review]

File: lib/Service/ConfigService.php (hunk 1 above)
Comment (juliushaertl) [reply lib/Service/ConfigService.php:68]: No, that would basically not explode the value at all:

> If limit is set and positive, **the returned array will contain a maximum of limit elements with the last element containing the rest of string**.

````
$foo = explode(':', 'a:b:c:d', 1);
array(1) {
  [0]=>
  string(7) "a:b:c:d"
}
````
