### PR TITLE
Fix handling of notifications if a board does no longer exist

### LINKED ISSUE #2176: Trying to access array offset on value of type bool
Using Nextcloud 19.0.1 and Deck 1.0.5, I see thousands of this Errors.

```
[PHP] Error: Trying to access array offset on value of type bool at /var/www/html/custom_apps/deck/lib/Db/CardMapper.php#195

GET /ocs/v2.php/apps/notifications/api/v2/notifications

```

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #2176

### CODE REVIEW

**Review by acsfer — APPROVED** [review]
Tested and works. 👍

File: lib/Db/AclMapper.php [hunk 1]
```diff
@@ -43,8 +45,13 @@ public function isOwner($userId, $aclId): bool {
 	}
 
 	public function findBoardId($aclId): ?int {
-		$entity = $this->find($aclId);
-		return $entity->getBoardId();
+		try {
+			$entity = $this->find($aclId);
+			return $entity->getBoardId();
+		} catch (DoesNotExistException $e) {
+		} catch (MultipleObjectsReturnedException $e) {
```
Comment (acsfer) [inline lib/Db/AclMapper.php:52]: Cant these catch be merged as `catch (DoesNotExistException | MultipleObjectsReturnedException $e) {`?
